name: Lint Models

on:
  push:
    branches:
      - main

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.12"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint models
        run: "pwd && ls -lah && sqlfluff lint --dialect snowflake"
