name: Fix Models

on:
  push:
    branches:
      - main

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.12"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint models
        run: "sqlfluff lint tests/ --dialect snowflake"
        continue-on-error: true
      - name: Fix models
        run: "sqlfluff fix tests/ --dialect snowflake"
